FROM ubuntu:16.04

RUN apt-get -y update
RUN apt-get -y install default-jre
COPY build/libs/serve.jar /
ENV DRIVERLESS_AI_LICENSE_FILE=/opt/ml/model/license.sig

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "/serve.jar"]
