name: Trivy & Prisma Scan

on:
  schedule:
    - cron: '30 2 * * 1-5'

jobs:
  build:
    uses: ./.github/workflows/image-build.yml
    secrets: inherit

  security_scan:
    name: Security Scan
    uses: ./.github/workflows/component-scan.yml
    needs: build
    secrets: inherit
