name: Build Images

on:
  workflow_call:
    inputs:
      if:
        description: Whether to run the workflow (workaround for required status checks issue)
        type: boolean
        default: true
      component_version:
        description: Gradle component version
        required: true
        type: string

jobs:
  build:
    name: Build Image
    if: ${{ inputs.if }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build images with Gradle Wrapper
        run: |
          ./gradlew :local-rest-scorer:build -Pversion=${{ inputs.component_version }} -x check  --init-script init.gradle
          docker build -t image:latest -f local-rest-scorer/Dockerfile local-rest-scorer

      - name: Save docker image
        run:  docker save image:latest > /tmp/image.tar

      - name: Save image artifact
        uses: actions/upload-artifact@v4
        with:
          name: image
          path: /tmp/image.tar
          compression-level: 0
