name: Trivy & Prisma Scan

on:
  schedule:
    - cron: '30 2 * * 1-5'

jobs:
  setup_env:
    uses: ./.github/workflows/setup-environment.yml

  build:
    uses: ./.github/workflows/image-build.yml
    needs: setup_env
    secrets: inherit
    with:
      component_version: ${{ needs.setup_env.outputs.component_version }}

  security_scan:
    name: Security Scan
    uses: ./.github/workflows/component-scan.yml
    needs: build
    secrets: inherit
