name: Publish images from Feature Branches

on:
  workflow_dispatch:

jobs:
  setup_env:
    uses: ./.github/workflows/setup-environment.yml

  build_from_branch:
    needs: setup_env
    uses: ./.github/workflows/image-build.yml
    secrets: inherit
    with:
      component_version: ${{ needs.setup_env.outputs.component_version }}

  publish_from_branch:
    uses: ./.github/workflows/image-publish.yml
    needs:
      - setup_env
      - build_from_branch
    secrets: inherit
    with:
      ecr_mlops_push_enabled: true
      ecr_h2o_push_enabled: false
      ecr_mc_push_enabled: false
      image_tags: "branch-${{ needs.setup_env.outputs.sanitized_branch_name }}-${{ needs.setup_env.outputs.commit_hash }}"
