name: Publish images from Feature Branches

on:
  workflow_dispatch:

jobs:
  setup_env:
    uses: ./.github/workflows/setup-environment.yml

  build_from_branch:
    needs: setup_env
    uses: ./.github/workflows/image-build.yml
    secrets: inherit
    with:
      component_version: ${{ needs.setup_env.outputs.component_version }}

  publish_from_branch:
    uses: ./.github/workflows/image-publish.yml
    needs:
      - setup_env
      - build_from_branch
    secrets: inherit
    with:
      gar_push_enabled: true
      gar_image_name: us-docker.pkg.dev/vorvan/mlops-dev/h2oai-modelscoring-restscorer
      ecr_push_enabled: false
      image_tags: "${{ needs.setup_env.outputs.sanitized_branch_name }}-${{ needs.setup_env.outputs.commit_hash }}"

