name: Check PR Title

on:
  pull_request:
    types: [ opened, reopened, synchronize, edited ]
    branches:
      - 'main'
      - 'release/[0-9]+.[0-9]+'

jobs:
  pr_title_check:
    name: Check PR Title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
